Description: Creates the `commbot` lambda functions

Parameters:
  CommbotLambdaRoleArn:
    Description: Arn name for the role running the lambda functions
    Type: String
  S3BucketName:
    Description: Bucket where the up-to-date lambda code lives.
    Type: String
  S3KeyName:
    Description: S3 Key with the up-to-date lambda code.
    Type: String
  PocketRssURL:
    Description: URL for the Pocket RSS feed to retrieve recently read articles.
    Type: String
  TwitterConsumerKey:
    Description: API consumer key for Twitter
    Type: String
  TwitterConsumerSecret:
    Description: API consumer secret for Twitter
    Type: String
  TwitterAccessToken:
    Description: API access token for Twitter
    Type: String
  TwitterAccessSecret:
    Description: API access secret for Twitter
    Type: String

Resources:
  PocketRSSLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: commbot-pocket-rss-lambda
      Handler: pocket
      Runtime: go1.x
      Description: Retrieves recently read articles from the Pocket RSS feed
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3KeyName
      MemorySize: 128
      Timeout: 10
      Role: !Ref CommbotLambdaRoleArn
      Environment:
        Variables:
          POCKET_RSS_URL: !Ref PocketRssURL
  
  TwitterPostLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: commbot-twitter-post-lambda
      Handler: twitter
      Runtime: go1.x
      Description: Posts message to Twitter
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3KeyName
      MemorySize: 128
      Timeout: 10
      Role: !Ref CommbotLambdaRoleArn
      Environment:
        Variables:
          TWITTER_CONSUMER_KEY: !Ref TwitterConsumerKey
          TWITTER_CONSUMER_SECRET: !Ref TwitterConsumerSecret
          TWITTER_ACCESS_TOKEN: !Ref TwitterAccessToken
          TWITTER_ACCESS_SECRET: !Ref TwitterAccessSecret

  Ephemeral:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ephemeral-twitter
      Handler: ephemeral
      Runtime: go1.x
      Description: Deletes posts from Twitter
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3KeyName
      MemorySize: 128
      Timeout: 10
      Role: !Ref CommbotLambdaRoleArn
      Environment:
        Variables:
          TWITTER_CONSUMER_KEY: !Ref TwitterConsumerKey
          TWITTER_CONSUMER_SECRET: !Ref TwitterConsumerSecret
          TWITTER_ACCESS_TOKEN: !Ref TwitterAccessToken
          TWITTER_ACCESS_SECRET: !Ref TwitterAccessSecret
