version: 0.2
phases:
  install:
    commands:
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  pre_build:
    commands:
      - mkdir -p /go/src/github.com/jared-prime
      - ln -s $(pwd) /go/src/github.com/jared-prime/commbot
      - dep ensure -vendor-only
      - ls /go/src/github.com/
  build:
    commands:
      - go build -o bin/twitter lambda/main.go
artifacts:
  files:
      - bin/twitter    
cache:
  paths:
    - bin