Description: Builds a `commbot` stack within AWS

Parameters:
  GithubUsername:
    Description: Github user for the commbot source code
    Default: jared-prime
    Type: String
  GithubRepository:
    Description: Github repository name for the commbot source code
    Default: commbot
    Type: String
  GithubBranch:
    Description: Github branch name to watch for changes
    Default: master
    Type: String
  GithubOAuthToken:
    Description: Github authorization token
    Type: String
  PocketRssURL:
    Description: URL for the Pocket RSS feed to retrieve recently read articles.
    Type: String
  TwitterConsumerKey:
    Description: API consumer key for Twitter
    Type: String
  TwitterConsumerSecret:
    Description: API consumer secret for Twitter
    Type: String
  TwitterAccessToken:
    Description: API access token for Twitter
    Type: String
  TwitterAccessSecret:
    Description: API access secret for Twitter
    Type: String

Resources:
  CommbotBucket:
    Type: AWS::S3::Bucket

  UpdatePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource: !Sub arn:aws:s3:::${CommbotBucket}/*
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: "*"

  CommbotBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectVersion
                Resource: !Sub arn:aws:s3:::${CommbotBucket}/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  CommbotBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-commbot-build
      ServiceRole: !Ref CommbotBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: .aws/codebuild/spec.yaml
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/golang:1.10
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: S3_KEY
            Value: lambda.zip
          - Name: S3_BUCKET
            Value: !Ref CommbotBucket
          - Name: PACKAGE_NAME
            Value: !Sub github.com/${GithubUsername}/${GithubRepository}

  PipelineCloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:GetFunction
                  - lambda:CreateFunction
                  - lambda:PublishVersion
                  - lambda:UpdateFunctionCode
                  - lambda:TagResource
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:GetRole
                  - iam:PassRole
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: "*"

  UpdatePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt UpdatePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref CommbotBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Github
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Ref GithubUsername
                Repo: !Ref GithubRepository
                Branch: !Ref GithubBranch
                OAuthToken: !Ref GithubOAuthToken
              OutputArtifacts:
                - Name: SourceCode
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build-Lambda-Functions
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CommbotBuild
              InputArtifacts:
                - Name: SourceCode
              RunOrder: 1
        - Name: Deployment
          Actions:
            - Name: CreateOrUpdateLambdaFunctions
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ChangeSetName: Deploy
                ActionMode: CREATE_UPDATE
                StackName: !Sub ${AWS::StackName}-lambdas
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: SourceCode::.aws/lambda/template.yaml
                RoleArn: !GetAtt PipelineCloudFormationRole.Arn
                ParameterOverrides: !Sub |
                  {
                    "S3BucketName": "${CommbotBucket}",
                    "S3KeyName": "lambda.zip",
                    "PocketRssURL": "${PocketRssURL}",
                    "TwitterConsumerKey": "${TwitterConsumerKey}",
                    "TwitterConsumerSecret": "${TwitterConsumerSecret}",
                    "TwitterAccessToken": "${TwitterAccessToken}",
                    "TwitterAccessSecret": "${TwitterAccessSecret}"
                  }
              InputArtifacts:
                - Name: SourceCode
              RunOrder: 1

Outputs:
  PipelineUrl:
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${UpdatePipeline}